"""Message templates for the synthetic Indian SMS / WhatsApp corpus.

Each category has a list of templates. `{slot}` markers are filled by
`ml.generate_dataset`. Templates whose index satisfies `i % 4 == 3` are HELD OUT:
they only ever appear in the test split, so the reported metrics measure how well
the model generalises to message *wordings it has never seen*, not just to new
slot values.
"""

SCAM_CATEGORIES = [
    "kyc_bank",
    "upi_collect",
    "job_task",
    "lottery_prize",
    "loan_app",
    "delivery_courier",
    "electricity_bill",
    "otp_harvest",
    "investment_crypto",
    "sextortion_threat",
]
SAFE_CATEGORIES = ["legit_transactional", "promotional", "personal"]
ALL_CATEGORIES = SCAM_CATEGORIES + SAFE_CATEGORIES

CATEGORY_LABELS = {
    "kyc_bank": "KYC / bank impersonation",
    "upi_collect": "UPI collect-request fraud",
    "job_task": "Fake job / task scam",
    "lottery_prize": "Lottery / prize",
    "loan_app": "Loan app",
    "delivery_courier": "Delivery / courier",
    "electricity_bill": "Electricity bill disconnection",
    "otp_harvest": "OTP harvesting",
    "investment_crypto": "Investment / crypto",
    "sextortion_threat": "Sextortion / threat",
    "legit_transactional": "Legit transactional",
    "promotional": "Promotional",
    "personal": "Personal",
}

TEMPLATES: dict[str, list[str]] = {
    "kyc_bank": [
        "Dear {bank} customer, your account will be blocked today due to pending KYC. Update PAN immediately: {scam_url}",
        "{bank_short} ALERT: Your YONO/NetBanking access is suspended. Complete KYC within 24 hrs by clicking {scam_url} to avoid freezing of account.",
        "Dear Customer your {bank} a/c {acct} is temporarily blocked. Pls update your KYC now {scam_url} or call {phone}",
        "Your {bank_short} debit card will be deactivated tonight. Link Aadhaar with your account urgently at {scam_url}",
        "Dear user, aapka {bank} account aaj band ho jayega. KYC update karne ke liye is link par click kare {scam_url}",
        "{bank} Notice: PAN card not updated. Your account {acct} will be closed in 24 hours. Update here {scam_url}",
        "Your {bank_short} reward points worth {amt} expire today. Redeem now by entering card details at {scam_url}",
        "Dear valued customer, due to RBI guidelines your {bank} account needs re-verification. Call our KYC officer on {phone} immediately.",
        "ATTENTION: {bank_short} account holder, your netbanking is locked due to incomplete e-KYC. Download the update app {apk_url}",
        "Sir your {bank} credit card limit increase request is pending. Verify details at {scam_url} before {date} or request will be cancelled",
        "Dear customer your {bank_short} account has been suspended!! pls update ur pan no. immediatly {scam_url}",
        "{bank} KYC expired. Account freeze from today. Contact customer care {phone} and share details to reactivate.",
        "Priya madam, this is from {bank} head office. Your KYC is pending, kindly install AnyDesk so our executive can update it for you.",
        "IMPORTANT: Your {bank_short} account {acct} is on hold. Verify identity within 2 hours at {scam_url} else permanent block.",
        "Aapka {bank_short} ATM card block kar diya gaya hai. Dobara chalu karne ke liye {phone} par call kare turant.",
        "Dear {bank} user, suspicious login detected. Secure your account now {scam_url} - {bank_short} Security Team",
    ],
    "upi_collect": [
        "Congratulations! You have received a cashback of {amt}. Enter your UPI PIN to receive the money in your account.",
        "Hi, I am sending {amt} for the OLX item. Please accept the collect request from {scam_upi} and enter PIN to receive payment.",
        "{name} has requested money from you. Approve the request on {scam_upi} to get your refund of {amt}.",
        "Your {company} refund of {amt} is ready. Accept the UPI collect request and enter your PIN to credit it.",
        "Sir army wala hoon, payment advance bhej raha hu. Jo request aayi hai usme PIN daalo paise receive ho jayenge.",
        "Refund initiated for your order. Scan the QR code sent on WhatsApp and enter UPI PIN to receive {amt}.",
        "PhonePe cashback {amt} pending. Click {upi_link} and enter your PIN to claim it now.",
        "To receive {amt} from {company} please approve the collect request from {scam_upi}. Request expires in 10 minutes.",
        "Bhai maine {amt} bheja hai, galti se. Please jo request bheji hai use approve kar do, PIN daal ke paise wapas kar do.",
        "Dear customer, your electricity refund of {amt} is approved. Pay Rs 1 to {scam_upi} to verify and receive the refund.",
        "Your Google Pay reward of {amt} is waiting. Tap the request from {scam_upi} and enter PIN to receive.",
        "I am buyer for your sofa on OLX. I have sent {amt} request, just accept and put UPI pin, money will come to you.",
        "Cashback alert! {amt} credited in your wallet. Enter UPI PIN on request {scam_upi} to move to bank.",
        "Paytm KYC refund {amt}: approve collect request from {scam_upi} to get money back instantly.",
    ],
    "job_task": [
        "Hello, we are hiring part-time staff. Earn {small_amt} to {big_amt} daily by liking YouTube videos. WhatsApp {phone}",
        "Work from home job! Simple tasks, daily salary {big_amt}. No experience needed. Contact HR {name} on {phone}",
        "Hi, I am {name} from {company} HR. You are selected for online part time job. Reply YES to start earning {small_amt} per task.",
        "Earn money by rating hotels on Google Maps. {small_amt} per review, withdraw instantly. Join telegram {tg_link}",
        "Ghar baithe kamaye {big_amt} roz. Sirf 30 min kaam. Abhi WhatsApp kare {phone}",
        "Dear candidate, your resume is shortlisted for data entry job. Pay registration fee {small_amt} to {scam_upi} to confirm.",
        "Part time job offer: complete prepaid tasks and get 30% commission. First task {small_amt} return {big_amt}. Link {scam_url}",
        "Congratulations, you are selected for Amazon work from home. Salary {big_amt}/month. Pay training fee to {scam_upi}",
        "Hello dear, looking for extra income? Subscribe to channels & get paid {small_amt} each. Message me on telegram {tg_link}",
        "Urgent hiring! Typing job, earn {big_amt} weekly. Security deposit refundable {small_amt}. Call {phone}",
        "Job vacancy in {company}. Online task, daily payout {big_amt}. Click {scam_url} to register now, limited seats",
        "Hi I am {name}, recruiter. Simple like and follow tasks, earn {big_amt} per day. Interested? reply on WhatsApp",
        "Aapko {company} me online job mili hai. Joining fee {small_amt} bhejiye {scam_upi} par aur aaj se kaam shuru kare.",
        "Earn {big_amt} daily with our merchant task platform. Recharge {small_amt} and get double commission. {scam_url}",
    ],
    "lottery_prize": [
        "Congratulations! Your mobile number has won {big_amt} in KBC lucky draw. Call {phone} to claim your prize.",
        "You have won a Tata Safari in the {company} anniversary lucky draw! Pay processing fee {small_amt} to claim.",
        "Dear winner, your number is selected for Jio lottery prize of {big_amt}. Contact manager {name} on WhatsApp {phone}",
        "Your SIM has won {big_amt} from Airtel lucky draw 2026. To claim send your bank details to {email}",
        "Badhai ho! Aapne KBC me {big_amt} jeete hain. Lottery claim karne ke liye {phone} par call kare.",
        "WINNER!! You are selected for a free iPhone 16 from {company}. Claim within 24 hours at {scam_url}",
        "Congratulations dear, you won {big_amt} in the Coca Cola promo. Pay GST charges {small_amt} to {scam_upi} to receive prize.",
        "Your email ID won GBP 850,000 in the UK National Lottery. Send name, address and account no to claim.",
        "Lucky draw result: your mobile number is winner of {big_amt}. Registration fee {small_amt} only. {scam_url}",
        "{company} spin & win: you won a gold coin! Pay delivery charge {small_amt} at {scam_url}",
        "Dear customer you have been selected in Diwali bumper draw. Prize {big_amt}. Call now {phone}",
        "Mubarak ho, aapka number {big_amt} ke inam ke liye chuna gaya hai. Abhi claim kare {scam_url}",
        "You have won a scratch card of {amt}. Scratch now before it expires: {scam_url}",
    ],
    "loan_app": [
        "Instant loan approved! Get {big_amt} in 5 minutes without CIBIL check. Download {loan_app} {apk_url}",
        "Pre-approved personal loan of {big_amt} at 0% interest. Pay file charge {small_amt} to {scam_upi} to disburse today.",
        "Your loan from {loan_app} is overdue. Pay {amt} today or your photos will be sent to all your contacts.",
        "Need money urgently? {loan_app} gives loan in 10 min, only Aadhaar and PAN required. {scam_url}",
        "Loan chahiye? Bina document {big_amt} tak ka loan turant. Abhi apply kare {apk_url}",
        "Dear {name}, your {loan_app} EMI is late. Pay now or we will call your family and office. Pay to {scam_upi}",
        "Congratulations, {big_amt} loan sanctioned. Pay insurance charge {small_amt} before disbursement. Call {phone}",
        "FINAL WARNING: Loan recovery team will visit your home today. Clear dues {amt} immediately at {scam_url}",
        "Get loan up to {big_amt} with low CIBIL. Processing fee refundable. WhatsApp {phone}",
        "{loan_app}: Your loan limit increased to {big_amt}. Install the new app version {apk_url} to withdraw.",
        "You have an unpaid loan of {amt}. Your morphed photos will be shared on social media if not paid in 2 hours.",
        "Sasta loan sirf 1% byaaj par. Approval pakka. Registration fee {small_amt} {scam_upi} par bheje.",
    ],
    "delivery_courier": [
        "{courier}: Your parcel is on hold due to incomplete address. Update within 12 hours: {scam_url}",
        "Your package could not be delivered. Pay redelivery fee of Rs 25 at {scam_url}",
        "{courier} alert: shipment {awb} held at customs. Pay clearance charge {small_amt} to release.",
        "Dear customer, your {company} order is returned due to wrong pin code. Reschedule delivery {scam_url}",
        "Aapka parcel address galat hone ki wajah se ruk gaya hai. Address update kare {scam_url}",
        "This is {courier}. A parcel in your name contains illegal items and is seized. Press 1 to talk to officer or call {phone}",
        "Your shipment {awb} is pending. Confirm your address and pay Rs 12 service fee here {scam_url}",
        "{courier}: We tried to deliver your package today. Book a new slot now {scam_url} or it will be returned.",
        "Dear user your courier from abroad has arrived, pay customs duty {amt} to {scam_upi} for delivery.",
        "Final notice: undeliverable package {awb}. Update details in 24 hrs at {scam_url}",
        "{courier} India: parcel address incomplete!! click to fix {scam_url}",
        "Your FedEx parcel has drugs and fake passports. Mumbai police will contact you. Call {phone} immediately.",
    ],
    "electricity_bill": [
        "Dear consumer, your electricity power will be disconnected tonight at 9.30 pm because your previous month bill was not updated. Contact officer {phone}",
        "{discom}: Your electricity connection will be cut today. Please call our electricity officer {phone} immediately.",
        "Dear customer, your light bill is pending. Power will be disconnected at 10 PM. Call {phone} to update.",
        "Aapka bijli connection aaj raat kaat diya jayega. Pichla bill update nahi hua hai. Turant sampark kare {phone}",
        "Electricity Board: Your meter is not updated. Download app {apk_url} and pay Rs 10 to avoid disconnection.",
        "Dear consumer your electricity bill {amt} is unpaid. Pay immediately at {scam_url} or supply will be stopped.",
        "{discom} NOTICE: Power cut today 9 PM due to KYC pending. Call {phone} for update.",
        "Dear Consumer, Electricity Power will be disconnected. Your previous month bill was not update. Plz contact {phone}",
        "Your {discom} account is suspended due to unpaid bill. Pay {amt} via {scam_upi} now to restore.",
        "URGENT: bijli bill jama nahi hua. Aaj raat 9 baje light kat jayegi. Call karein {phone}",
        "Dear user your electricity connection is scheduled for disconnection. Install QuickSupport app and call {phone}",
        "Last reminder from electricity department: update bill details at {scam_url} to avoid power cut tonight.",
    ],
    "otp_harvest": [
        "Hi, I sent you an OTP by mistake. Please forward it to me, it is urgent.",
        "This is {bank} customer care. To stop the unauthorized transaction please tell us the OTP you just received.",
        "Dear customer, share the 6 digit code sent to your phone to verify your {company} account.",
        "Bhai galti se tumhare number pe OTP aa gaya, please bhej do jaldi.",
        "{bank_short} Security: To cancel the debit of {amt}, reply with the OTP received on your mobile.",
        "Hello, I am from {company} delivery. Please tell me the OTP to complete your delivery and refund.",
        "Your WhatsApp account will be deleted. Send the verification code you received to {phone} to keep it active.",
        "Dear user, to receive your {company} gift, share the OTP received now with our executive.",
        "Sir main bank se bol raha hu, aapke phone par jo OTP aaya hai woh batayiye card block hone se bachane ke liye.",
        "Please share the OTP sent to you, I need to verify my Paytm account urgently. Will explain later.",
        "Kindly send the one time password received to complete your KYC verification with {bank}.",
        "Your SIM will be blocked in 2 hours. Share the code received via SMS with {phone} to upgrade to 5G.",
    ],
    "investment_crypto": [
        "Join our VIP stock tips group and earn 300% returns in 7 days. Guaranteed profit. {tg_link}",
        "Invest {small_amt} and get {big_amt} in 24 hours. Crypto trading with {crypto_app}. Limited slots {scam_url}",
        "Hello sir, {crypto_app} gives 5% daily return on USDT deposits. Register now {scam_url}",
        "Double your money in 30 days! Safe investment plan, guaranteed returns. WhatsApp {phone}",
        "Paisa double karo sirf 15 din me. Crypto me invest kare, profit pakka. Join {tg_link}",
        "Exclusive IPO allotment via our institutional account. Deposit to {scam_upi} and get 40% listing gain.",
        "Dear investor, your trading account shows profit {big_amt}. Pay withdrawal tax {small_amt} to release funds.",
        "Bitcoin mining opportunity: earn {big_amt} weekly with no risk. Sign up at {scam_url}",
        "Our SEBI registered expert gives 100% accurate intraday calls. Pay {small_amt} for lifetime membership {scam_upi}",
        "{crypto_app} app: you received bonus {amt}. Deposit more to unlock withdrawals. {scam_url}",
        "Hi, I made {big_amt} last month with this forex app. You can too, start with just {small_amt}. {scam_url}",
        "Stock market secret group! Daily 20% profit guaranteed. Add me on WhatsApp {phone}",
    ],
    "sextortion_threat": [
        "I have recorded your video call. Pay {amt} to {scam_upi} or I will send it to all your contacts.",
        "This is CBI cyber cell. A case is registered against you for viewing illegal content. Pay fine {amt} to avoid arrest.",
        "Your private video will be uploaded on YouTube in 1 hour. Pay now to delete. Contact {phone}",
        "Tumhari video mere paas hai. {amt} bhejo warna sab ko bhej dunga.",
        "Delhi Police: an FIR has been filed in your name. You are under digital arrest. Join video call on {phone} immediately.",
        "We have your photos and contacts list. Pay {amt} within 2 hours or they will be made viral.",
        "Crime branch notice: your Aadhaar is linked to money laundering. Do not tell anyone. Call {phone} now.",
        "I hacked your phone and have your videos. Send {amt} in bitcoin or everyone will see them.",
        "Sir aapka video viral ho jayega. YouTube se delete karwane ke liye {amt} bheje {scam_upi}",
        "Mumbai cyber police: warrant issued against your number. Pay settlement {amt} to close the case.",
        "Last warning. Your video is ready to be sent to your family. Pay {amt} now to {scam_upi}.",
    ],
    "legit_transactional": [
        "{otp} is your OTP for transaction of {amt} at {company} on {bank_short} card {acct}. Valid for 10 mins. Do not share it with anyone. -{bank}",
        "Your a/c {acct} is debited with {amt} on {date} for UPI/{ref}. If not you, call 1800-425-3800. -{bank_short}",
        "Dear Customer, {amt} credited to your A/c {acct} on {date} by NEFT. Avl Bal {amt2}. -{bank}",
        "{otp} is the OTP to log in to {company}. Never share this code with anyone, including {company} staff.",
        "Your order for {item} has been shipped via {courier}. Track: {legit_url}",
        "Sent {amt} from {bank_short} A/c {acct} to {name} on {date}. UPI Ref {ref}. Not you? Call 18001801290",
        "Dear {name}, your {company} order #{order} is out for delivery today. Delivery agent will call you.",
        "OTP for your {company} delivery is {otp}. Share it with the delivery agent only after receiving the package.",
        "{discom}: Bill of {amt} for consumer no {ref} generated. Due date {date}. Pay via official app or {legit_url}",
        "Your {bank_short} Credit Card statement is ready. Total due {amt}, min due {small_amt}, due by {date}.",
        "Use OTP {otp} to verify your mobile number on {company}. The OTP is valid for 5 minutes. Do not share.",
        "Recharge of {small_amt} successful for {phone}. Validity 28 days. Thank you for choosing Airtel.",
        "Dear customer, EMI of {amt} for loan a/c {acct} is due on {date}. Maintain sufficient balance. -{bank}",
        "Your {courier} shipment {awb} is delivered. Thank you for shopping with {company}.",
        "{amt} received from {name} in your Paytm wallet. Updated balance {amt2}.",
        "Your KYC is successfully updated for {bank} a/c {acct}. No further action needed. -{bank_short}",
        "Your electricity bill payment of {amt} to {discom} is successful. Txn ID {ref}.",
        "Refund of {amt} for your {company} order #{order} has been processed to your original payment method. It will reflect in 5-7 days.",
        "{bank_short}: Card {acct} used for {amt} at {company} on {date}. Not you? Block card via {bank_short} app or call helpline.",
        "Dear {name}, your appointment at Apollo Clinic is confirmed for {date} {time}. Reply C to cancel.",
        "IRCTC: PNR {ref} booked for {date}. Train 12627, Coach B2, Seat 34. Happy journey.",
        "Your cheque no {otp} for {amt} has been cleared. -{bank}",
        "OTP {otp} for your UPI PIN reset. {bank_short} never asks for OTP or PIN over call. Do not share.",
        "Money received! {amt} from {name} ({legit_upi}) credited to your {bank_short} account. UPI Ref {ref}",
        "UPI: {amt} credited to your a/c {acct} from {legit_upi} on {date}. Ref no {ref}. -{bank_short}",
        "Your {company} order #{order} has been placed. Estimated delivery by {date}.",
        "Dear customer, {amt} received in your account {acct} via IMPS from {name}. Balance {amt2}.",
        "{bank_short}: Your FD of {amt} has matured and been credited to a/c {acct}.",
        "Aapke {bank_short} khate {acct} me {amt} jama kiye gaye hain. Upalabdh shesh {amt2}.",
        "Your Jio number has been recharged with Rs 299. Plan valid till {date}. Enjoy!",
        "Dear {name}, your salary of {amt} for this month has been credited. -{bank}",
        "Payment of {amt} to {company} successful. UPI Ref {ref}. Download invoice from the app.",
    ],
    "promotional": [
        "Big Billion Days are here! Up to 80% off on mobiles at {company}. Shop now {legit_url}",
        "Flat 50% off on your next order at Swiggy. Use code TASTY50. T&C apply.",
        "{company} End of Season Sale: extra 10% off with {bank_short} cards. Hurry, offer ends Sunday.",
        "Get 2GB extra data with Jio Rs 299 plan. Recharge now on MyJio app.",
        "Your favourite brands at lowest prices. Myntra EORS starts tonight. {legit_url}",
        "Upgrade to a {bank_short} Platinum credit card with lifetime free benefits. Apply on {legit_url}",
        "Weekend special: buy 1 get 1 free on all pizzas at Domino's. Order online.",
        "Dear customer, enjoy 20% cashback up to Rs 100 on bill payments via Amazon Pay this week.",
        "New arrivals at {company}! Kurtas starting Rs 399. Shop now. To unsubscribe reply STOP.",
        "{bank}: Pre-qualified offer! Personal loan up to {big_amt} at attractive rates. Check eligibility in the {bank_short} app. T&C apply.",
        "Diwali dhamaka at Reliance Digital - no cost EMI on TVs and ACs. Visit your nearest store.",
        "Book movie tickets on BookMyShow and get Rs 75 off with code MOVIE75.",
        "Swiggy Instamart: groceries delivered in 10 minutes. Free delivery on your first 3 orders.",
        "Get your car serviced at Maruti Suzuki with 15% off on labour. Book slot at {legit_url}",
        "Zomato Gold is back! Unlimited free deliveries for 3 months at Rs 30.",
        "Nykaa Pink Friday Sale is live. Up to 50% off on top beauty brands. {legit_url}",
        "Learn Python with our weekend bootcamp. Early bird fee Rs 1,999. Register at {legit_url}",
        "Aapke liye special offer! Vi Rs 199 recharge par 1GB extra data. Aaj hi recharge kare.",
        "Flat Rs 150 cashback on your first UPI payment with Amazon Pay. Offer valid till {date}. T&C apply.",
        "Get 10% cashback on electricity bill payments with Paytm this weekend. Use code POWER10.",
        "{company} Great Freedom Sale starts {date}. Extra 10% off with {bank_short} cards.",
        "Airtel: Get Disney+ Hotstar free with Rs 399 recharge. Recharge now on Airtel Thanks app.",
        "Is Diwali, ghar sajaiye {company} ke saath. 60% tak ki chhoot. Abhi shop kare.",
        "Refer a friend to {company} and both get Rs 100 off on the next order.",
    ],
    "personal": [
        "Hey {name}, are we still meeting at 6 today?",
        "Mom, I reached the hostel. Will call you after dinner.",
        "Bhai kal ka match dekhne chalega? Tickets mere paas hain.",
        "Can you send me the notes for DBMS unit 3? Exam is on {date}.",
        "Happy birthday {name}! Have a great year ahead.",
        "I've paid {small_amt} for the cab, send your share on GPay when free.",
        "Running 10 mins late, traffic near Silk Board is terrible.",
        "Papa ne bola hai shaam ko sabzi le aana. Aloo, tamatar aur dhaniya.",
        "Meeting moved to {time} tomorrow. Please update the slides before that.",
        "Thanks for dinner yesterday, the biryani was amazing!",
        "Did you submit the assignment? The portal closes at midnight.",
        "Kal college nahi aa raha, fever hai. Attendance laga dena please.",
        "Sending you the flat rent for this month, {amt}. Please confirm once received.",
        "{name} here, this is my new number. Save it.",
        "Can you pick up the parcel from the society gate? I am in office.",
        "Aaj dinner me kya banega? Main 8 baje tak aa jaunga.",
        "Congratulations on the new job {name}! Party kab hai?",
        "Reminder: Sunday cricket at 7am, bring the stumps.",
        "Beta khana kha liya? Papa puch rahe the.",
        "Yaar notes bhej de na, kal test hai.",
        "Main station pahunch gaya, tu kahan hai?",
        "Didi ki shaadi ki date fix ho gayi, {date}. Chhutti le lena.",
        "Bhaiya aaj gaadi service pe de di hai, shaam ko le aana.",
        "Mummy ne kaha hai kal subah jaldi uthna, mandir jaana hai.",
        "Kya scene hai weekend ka? Goa chalein?",
        "Paise mil gaye, thanks bro. Kal milte hain.",
        "Ok done. I'll send the report by {time}.",
        "Aaj office me late ho jayega, dinner pe wait mat karna.",
        "{name} ka phone nahi lag raha, usse bolna mujhe call kare.",
        "Did you reach home safely? Text me when you do.",
    ],
}
